# Site settings
title: First Left after the Light
header-img: img/home-bg.jpg
description: "You can't miss it"
baseurl: ""


# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
