# Site settings
title: Fleek Street Tech Blog
header-img: img/home-bg.jpg
description: "Tech Stuff, kept Simple"
baseurl: ""


# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
